#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd.
# username user id Home directory path for the user

FL="/etc/passwd" #FILELOCATION
while read FIELD
do
    echo "$FIELD" | cut -d ":" -f1,3,6
done < "$FL"
