#!/usr/bin/env bash
# loops from 1 to 10, "bad luck" on 4, "good luck" on the 8th.

i=0
while (( i <= 9));
do
    if (( i == 3)); then
        echo "bad luck"

    elif ((i == 7)); then
        echo "good luck"

    else
        echo "Best School"
    fi
    (( i++ ))

done
