#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
# display hours from 0 to 12 and display minutes from 1 to 59

h=0
m=1
while (( "$h" <= 12 ))
do 
    echo "$h"
    ((h++));
done

while (( "$m" <= 59 ))
do
    echo "$m"
    ((m++));
done
