#!/usr/bin/env bash
# displays info of file 

FILE="school"

if [ -e $FILE ]; then
    echo "$FILE file exists"

    else "$FILE file does not exist"

    if [ -s "$FILE" ]; then
        echo "$FILE file is not empty"
    else 
        echo "$FILE file is empty"
    fi

    if [ -f "$FILE" ]; then
        echo "$FILE is a regular file"
    fi
fi
